### ISSUE TITLE
Upgrade to Cypht 1.4.0 once it's released

### ISSUE THREAD

**Issue by marclaporte** [YunoHost-Apps/cypht_ynh#10]
Cypht is in active development but packaged releases are infrequent. The active developers just use Git-master.

A positive point is that Git-master remains pretty stable. But a negative point is that platforms like YunoHost should be getting released/stable versions.

Cypht 1.3 is pretty old now.

Here is what we plan to solve before releasing 1.4.0:
https://github.com/jasonmunro/cypht/milestone/1

There is just one blocker https://github.com/jasonmunro/cypht/issues/573
and the others can wait for 1.5

**Comment by TheNomad11** [comment]
1.4.0 was released yesterday https://github.com/cypht-org/cypht/releases/tag/v1.4.0

**Comment by ericgaspar** [comment]
and has been update yesterday... https://github.com/YunoHost-Apps/cypht_ynh/pull/52
