### ISSUE TITLE
Invalid auth configuration

### ISSUE THREAD

**Issue by glonguetaud** [YunoHost-Apps/cypht_ynh#2]
Hi, 
This is my first issue...

After installing the app, I can't acces to the admin page and I keep having this message when I log in the main one : 
`Invalid auth configuration` 

What did I miss ? 

Thank you !

**Comment by ericgaspar** [comment]
I am not able to reproduce this issue...
are you using the credentials you set at install?

**Comment by glonguetaud** [comment]
I don't have to enter any credential, whenever I go to https://my-domain/cypht (even in a private browser) I have the message mentioned above. 
Thanks for your help !

**Comment by marclaporte** [comment]
@glonguetaud A lot has changed since your report 2 years ago. Can you please try again?

Thanks!

**Comment by glonguetaud** [comment]
Hi @marclaporte unfortunately, I don't use cypht anymore… 
Thank you anyway !

**Comment by marclaporte** [comment]
@glonguetaud If / when you come back, you will see a lot of improvements! https://github.com/cypht-org/cypht/releases

Soon Cypht 2.0.x is coming to YunoHost:
https://github.com/cypht-org/cypht/releases

@ericgaspar Please close this or provide me powers to do so.

Thanks!
