### ISSUE TITLE
Account & Settings Persistence Failure

### ISSUE THREAD

**Issue by Bcarr91** [YunoHost-Apps/cypht_ynh#62]
### Describe the bug

*A clear and concise description of what the bug is.*
Accounts added in Settings is not persistent across web browsers; settings also not carried over between instances.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.10.3 (stable)
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain: N/A
- Using, or trying to install package version/branch: 1.4.1~ynh1
- If upgrading, current package version: N/A

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*

- *If you used the webadmin, please perform the equivalent command from the CLI first.*
- *If the error occurs in your browser, explain what you did:*
   1. Logged into Cypht and added IMAP accounts from desktop Chrome browser
   2. Opened on iPhone & logged in
   3. Found accounts missing
   4. Opened in different browser on desktop and found accounts missing
   5. Refreshed in original Chrome browser and accounts still present
   6. Verified in original Chrome browser 'Site Settings > General' and did not find a persistence setting outside of "Don't save account password between logins' which is not "Checked" off.

> Verified in [Cypht Security documentation](https://www.cypht.org/security.html) that persistence is expected and supposed to be encrypted.
> Inspected Network settings in Chrome and did not immediately find errors.

### Expected behavior

Account and settings persistence.

### Logs

No relevant logs

*If applicable and useful, add screenshots to help explain your problem.*
![image](https://github.com/YunoHost-Apps/cypht_ynh/assets/62965777/9c32f43c-0fca-4529-9910-50164e3f880e)
![image](https://github.com/YunoHost-Apps/cypht_ynh/assets/62965777/4ab31f80-239a-4cd7-b4b1-0a4631eb0842)

**Comment by Bcarr91** [comment]
After digging through all of the settings, I finally found the issue: 'Settings > Save' and enter a password. 🤦‍♂️
![image](https://github.com/YunoHost-Apps/cypht_ynh/assets/62965777/d628d62c-0e49-4ecd-8e47-4151e905768f)

**Comment by marclaporte** [comment]
Related: https://github.com/cypht-org/cypht/issues/523
