### ISSUE TITLE
Cypht 2.0 is coming in a few weeks

### ISSUE THREAD

**Issue by marclaporte** [YunoHost-Apps/cypht_ynh#63]
More info: https://github.com/cypht-org/cypht/issues/879

Since it's a big release, I suggest to wait a few weeks after 2.0 to let the bugs be shaken out.

**Comment by marclaporte** [comment]
Cypht 2.0 will be pretty buggy for reasons explained here: https://github.com/cypht-org/cypht/issues/879

I recommend to wait for 2.1 or 2.2

**Comment by marclaporte** [comment]
Full list of changes: https://github.com/cypht-org/cypht/releases/tag/v2.0.0

One which may affect YunoHost's scripts: https://github.com/cypht-org/cypht/pull/823

**Comment by marclaporte** [comment]
> I recommend to wait for 2.1 or 2.2

We updated the https://github.com/cypht-org/cypht/wiki/Lifecycle and decided to have 2.0.1, 2.0.2, etc.

So here is: https://github.com/cypht-org/cypht/releases/tag/v2.0.1

2.0.x is still less stable than 1.4.x but it's getting better week by week.

I recommend to all Cypht users to test 2.0.1 in parallel with 1.4.x and report any bugs.

Can YunoHost permit to easily run Cypht 1.4.x and 2.0.x in parallel?

**Comment by rodriguezny** [comment]
> Full list of changes: https://github.com/cypht-org/cypht/releases/tag/v2.0.0
> 
> One which may affect YunoHost's scripts: [cypht-org/cypht#823](https://github.com/cypht-org/cypht/pull/823)

There are some weeks I started working on the migration of the config to .env but didn't finished it yet, I will follow with as 2.0.0 is released. The is still in progress in in the draft PR [https://github.com/YunoHost-Apps/cypht_ynh/pull/70](https://github.com/YunoHost-Apps/cypht_ynh/pull/70) I just created.

**Comment by rodriguezny** [comment]
> > I recommend to wait for 2.1 or 2.2
> 
> We updated the https://github.com/cypht-org/cypht/wiki/Lifecycle and decided to have 2.0.1, 2.0.2, etc.
> 
> So here is: https://github.com/cypht-org/cypht/releases/tag/v2.0.1
> 
> 2.0.x is still less stable than 1.4.x but it's getting better week by week.
> 
> I recommend to all Cypht users to test 2.0.1 in parallel with 1.4.x and report any bugs.
> 
> Can YunoHost permit to easily run Cypht 1.4.x and 2.0.x in parallel?

A possible way to run easily Cypht 1.4.x and 2.0.x in parallel is to update the manifest.toml resources.sources to have two options: resources.sources.main and resources.sources.lts, so users will have the choice to install the LTS version (1.4.x) or regular version(2.0.x), and then update the install script as the configuration handling changed from 1.4.x to 2.0.x. That is my idea unless YunoHost guys(@ericgaspar ,  etc) provided another way to run the two versions in parallel.

**Comment by marclaporte** [comment]
Cypht is gaining in stability with a good cadence of commits and thanks to a test plan: https://github.com/cypht-org/cypht/wiki/Test-IMAP-SMTP-&-JMAP-SMTP-with-Stalwart

Next version will be 2.1.0: https://github.com/cypht-org/cypht/issues/1050

I am comfortable for this one to be packaged as stable in Cypht. It will require PHP 8.1

**Comment by marclaporte** [comment]
We fixed a lot of bugs: https://github.com/cypht-org/cypht/releases/tag/v2.1.0
