### ISSUE TITLE
Upgrade to Cypht 2.2.0 once it's released

### ISSUE THREAD

**Issue by marclaporte** [YunoHost-Apps/cypht_ynh#73]
As I explained at https://github.com/YunoHost-Apps/cypht_ynh/issues/63, it was better for Cypht-Yunohost to stay on 1.4.x for a little while longer.

But 2.x is getting pretty stable now. I'd like to see a few more things fixed like:
- https://github.com/cypht-org/cypht/issues/1119
- https://github.com/cypht-org/cypht/issues/1076

Once we release 2.2.0, we'll be in a good place. And any reported regressions will get fixed fairly fast as the number of contributors has grown considerably:
https://openhub.net/p/cypht

While Cypht 1.4.x has security fixes until 2025-05-01, I don't think we should support two versions in Yunohost.
https://github.com/cypht-org/cypht/wiki/Lifecycle

@rodriguezny Please take the lead on this.

**Comment by rodriguezny** [comment]
> As I explained at #63, it was better for Cypht-Yunohost to stay on 1.4.x for a little while longer.
> 
> But 2.x is getting pretty stable now. I'd like to see a few more things fixed like:
> 
> * [FastCGI timeout (Not docker related) cypht-org/cypht#1119](https://github.com/cypht-org/cypht/issues/1119)
> * [Adding gmail oauth no longer working. cypht-org/cypht#1076](https://github.com/cypht-org/cypht/issues/1076)
> 
> Once we release 2.2.0, we'll be in a good place. And any reported regressions will get fixed fairly fast as the number of contributors has grown considerably: https://openhub.net/p/cypht
> 
> While Cypht 1.4.x has security fixes until 2025-05-01, I don't think we should support two versions in Yunohost. https://github.com/cypht-org/cypht/wiki/Lifecycle
> 
> @rodriguezny Please take the lead on this.

OK, noted!

**Comment by marclaporte** [comment]
Cypht 2.2.0 has been released!
https://github.com/cypht-org/cypht/releases/tag/v2.2.0

It's pretty good now. If you find any regressions vs 1.4x, please let us know at https://github.com/cypht-org/cypht/issues and we will fix quickly.
